<section xmlns="http://www.w3.org/1999/xhtml" id="error-handling" data-type="chapter"><h1>Error Handling</h1><p>Nobody likes dealing with errors. It's tedious, it's easy to get wrong, and it's usually
    just not as fun as planning out how your program is going to succeed. But error handling is
    important, and however much you don't like thinking about it, having your software fail due to
    poor error handling is worse.</p><p>Thankfully, OCaml has powerful tools for handling errors reliably and
  with a minimum of pain. In this chapter we'll discuss some of the different
  approaches in OCaml to handling errors, and give some advice on how to
  design interfaces that make error handling easier.</p><p>We'll start by describing the two basic approaches for reporting
  errors in OCaml: error-aware return types and exceptions.<a data-type="indexterm" id="erraware" data-primary="error-aware return types">&#xa0;</a><a data-type="indexterm" id="EHeraware" data-primary="error handling" data-secondary="error-aware return types">&#xa0;</a></p><section id="error-aware-return-types" data-type="sect1"><h1>Error-Aware Return Types</h1><p>The best way in OCaml to signal an error is to include that error in
    your return value. Consider the type of the <code>find</code> function in the <code>List</code> module:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a></p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>List.find;;</code></strong>
<code class="computeroutput">- : 'a list -&gt; f:('a -&gt; bool) -&gt; 'a option = &lt;fun&gt;</code></pre><p>The option in the return type indicates that the function may not
    succeed in finding a suitable element:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 1)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>List.find [1;2;3] ~f:(fun x -&gt; x &gt;= 2) ;;</code></strong>
<code class="computeroutput">- : int option = Some 2</code>
<code class="prompt"># </code><strong><code>List.find [1;2;3] ~f:(fun x -&gt; x &gt;= 10) ;;</code></strong>
<code class="computeroutput">- : int option = None</code></pre><p>Including errors in the return values of your functions requires the
    caller to handle the error explicitly, allowing the caller to make the
    choice of whether to recover from the error or propagate it onward.</p><p>Consider the <code>compute_bounds</code>
    function. The function takes a list and a comparison function and returns
    upper and lower bounds for the list by finding the smallest and largest
    element on the list. <code>List.hd</code> and
    <code>List.last</code>, which return <code>None</code> when they encounter an empty list, are used
    to extract the largest and smallest element of the list:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 2)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let compute_bounds ~cmp list =</code></strong>
<strong><code>    let sorted = List.sort ~cmp list in</code></strong>
<strong><code>    match List.hd sorted, List.last sorted with</code></strong>
<strong><code>    | None,_ | _, None -&gt; None</code></strong>
<strong><code>    | Some x, Some y -&gt; Some (x,y)</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val compute_bounds : cmp:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>The <code>match</code> statement is used to handle the error
    cases, propagating a <code>None</code> in <code>hd</code> or <code>last</code>
    into the return value of <code>compute_bounds</code>.</p><p>On the other hand, in the <code>find_mismatches</code> that follows, errors encountered
    during the computation do not propagate to the return value of the
    function. <code>find_mismatches</code> takes two
    hash tables as arguments and searches for keys that have different data in
    one table than in the other. As such, the failure to find a key in one
    table isn't a failure of any sort:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 3)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let find_mismatches table1 table2 =</code></strong>
<strong><code>     Hashtbl.fold table1 ~init:[] ~f:(fun ~key ~data mismatches -&gt;</code></strong>
<strong><code>        match Hashtbl.find table2 key with</code></strong>
<strong><code>        | Some data' when data' &lt;&gt; data -&gt; key :: mismatches</code></strong>
<strong><code>        | _ -&gt; mismatches</code></strong>
<strong><code>     )</code></strong>
<strong><code> ;;</code></strong>
<code class="computeroutput">val find_mismatches : ('a, 'b) Hashtbl.t -&gt; ('a, 'b) Hashtbl.t -&gt; 'a list =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>The use of options to encode errors underlines the fact that it's
    not clear whether a particular outcome, like not finding something on a
    list, is an error or is just another valid outcome. This depends on the
    larger context of your program, and thus is not something that a
    general-purpose library can know in advance. One of the advantages of
    error-aware return types is that they work well in both situations.</p><section id="encoding-errors-with-result" data-type="sect2"><h2>Encoding Errors with Result</h2><p>Options aren't always a sufficiently expressive way to report
      errors. Specifically, when you encode an error as <code>None</code>, there's nowhere to say anything about
      the nature of the error.</p><p><code>Result.t</code> is meant to address
      this deficiency. The type is defined as follows:<a data-type="indexterm" data-primary="Result.t option">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/result.mli" class="orm:hideurl:ital"><em class="hyperlink">OCaml</em></a></p><pre data-type="programlisting" data-code-language="ocaml">module Result : sig
   type ('a,'b) t = | Ok of 'a
                    | Error of 'b
end</pre><p>A <code>Result.t</code> is essentially an
      option augmented with the ability to store other information in the
      error case. Like <code>Some</code> and <code>None</code> for options, the constructors <code>Ok</code> and <code>Error</code> are promoted to the toplevel by <code>Core.Std</code>. As such, we can write:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 4)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>[ Ok 3; Error "abject failure"; Ok 4 ];;</code></strong>
<code class="computeroutput">- : (int, string) Result.t list = [Ok 3; Error "abject failure"; Ok 4]</code></pre><p>without first opening the <code>Result</code> module.</p></section><section id="error-and-or_error" data-type="sect2"><h2>Error and Or_error</h2><p><code>Result.t</code> gives you complete
      freedom to choose the type of value you use to represent errors, but
      it's often useful to standardize on an error type. Among other things,
      this makes it easier to write utility functions to automate common error
      handling patterns.<a data-type="indexterm" data-primary="Error.t type">&#xa0;</a></p><p>But which type to choose? Is it better to represent errors as
      strings? Some more structured representation like XML? Or something else
      entirely?</p><p>Core's answer to this question is the <code>Error.t</code> type, which tries to forge a good
      compromise between efficiency, convenience, and control over the
      presentation of errors.</p><p>It might not be obvious at first why efficiency is an issue at
      all. But generating error messages is an expensive business. An ASCII
      representation of a value can be quite time-consuming to construct,
      particularly if it includes expensive-to-convert numerical data.</p><p><code>Error</code> gets around this issue
      through laziness. In particular, an <code>Error.t</code> allows you to put off generation of
      the error string until and unless you need it, which means a lot of the
      time you never have to construct it at all. You can of course construct
      an error directly from a string:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 5)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Error.of_string "something went wrong";;</code></strong>
<code class="computeroutput">- : Error.t = something went wrong</code></pre><p>But you can also construct an <code>Error.t</code> from a <em>thunk</em>,
      i.e., a function that takes a single argument of type <code>unit</code>:<a data-type="indexterm" data-primary="thunks">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 6)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Error.of_thunk (fun () -&gt;</code></strong>
<strong><code>    sprintf "something went wrong: %f" 32.3343);;</code></strong>
<code class="computeroutput">- : Error.t = something went wrong: 32.334300</code></pre><p>In this case, we can benefit from the laziness of <code>Error</code>, since the thunk won't be called unless
      the <code>Error.t</code> is converted to a
      string.</p><p>The most common way to create <code>Error.t</code>s is using
      <em>s-expressions</em>. An s-expression is a balanced
      parenthetical expression where the leaves of the expressions are
      strings. Here's a simple example:<a data-type="indexterm" data-primary="s-expressions" data-secondary="example of">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/sexpr.scm" class="orm:hideurl:ital"><em class="hyperlink">Scheme</em></a></p><pre data-type="programlisting" data-code-language="scheme">(This (is an) (s expression))</pre><p>S-expressions are supported by the Sexplib package that is
      distributed with Core and is the most common serialization format used
      in Core. Indeed, most types in Core come with built-in s-expression
      converters. Here's an example of creating an error using the sexp
      converter for times, <code>Time.sexp_of_t</code>:<a data-type="indexterm" data-primary="Sexplib package" data-secondary="sexp converter">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 7)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Error.create "Something failed a long time ago" Time.epoch Time.sexp_of_t;;</code></strong>
<code class="computeroutput">- : Error.t =</code>
<code class="computeroutput">Something failed a long time ago: (1970-01-01 01:00:00.000000+01:00)</code></pre><p>Note that the time isn't actually serialized into an s-expression
      until the error is printed out.</p><p>We're not restricted to doing this kind of error reporting with
      built-in types. This will be discussed in more detail in <a href="#data-serialization-with-s-expressions" data-type="xref">#data-serialization-with-s-expressions</a>, but Sexplib comes
      with a language extension that can autogenerate sexp converters for
      newly generated types:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 8)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let custom_to_sexp = &lt;:sexp_of&lt;float * string list * int&gt;&gt;;;</code></strong>
<code class="computeroutput">val custom_to_sexp : float * string list * int -&gt; Sexp.t = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>custom_to_sexp (3.5, ["a";"b";"c"], 6034);;</code></strong>
<code class="computeroutput">- : Sexp.t = (3.5 (a b c) 6034)</code></pre><p>We can use this same idiom for generating an error:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 9)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Error.create "Something went terribly wrong"</code></strong>
<strong><code>    (3.5, ["a";"b";"c"], 6034)</code></strong>
<strong><code>    &lt;:sexp_of&lt;float * string list * int&gt;&gt; ;;</code></strong>
<code class="computeroutput">- : Error.t = Something went terribly wrong: (3.5(a b c)6034)</code></pre><p><code>Error</code> also supports operations
      for transforming errors. For example, it's often useful to augment an
      error with information about the context of the error or to combine
      multiple errors together. <code>Error.tag</code>
      and <code>Error.of_list</code> fulfill these
      roles:<a data-type="indexterm" data-primary="Error.of_list">&#xa0;</a><a data-type="indexterm" data-primary="Error.tag">&#xa0;</a><a data-type="indexterm" data-primary="errors" data-secondary="transformation of">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 10)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Error.tag</code></strong>
<strong><code>    (Error.of_list [ Error.of_string "Your tires were slashed";</code></strong>
<strong><code>                     Error.of_string "Your windshield was smashed" ])</code></strong>
<strong><code>    "over the weekend"</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">- : Error.t =</code>
<code class="computeroutput">over the weekend: Your tires were slashed; Your windshield was smashed</code></pre><p>The type <code>'a Or_error.t</code> is just
      a shorthand for <code>('a,Error.t)
      Result.t</code>, and it is, after <code>option</code>, the most common way of returning
      errors in Core.</p></section><section id="bind-and-other-error-handling-idioms" data-type="sect2"><h2>bind and Other Error Handling Idioms</h2><p>As you write more error handling code in OCaml, you'll discover
      that certain patterns start to emerge. A number of these common patterns
      have been codified by functions in modules like <code>Option</code> and <code>Result</code>. One particularly useful pattern is
      built around the function <code>bind</code>, which
      is both an ordinary function and an infix operator <code>&gt;&gt;=</code>. Here's the definition of <code>bind</code> for options:<a data-type="indexterm" data-primary="bind function">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 11)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let bind option f =</code></strong>
<strong><code>    match option with</code></strong>
<strong><code>    | None -&gt; None</code></strong>
<strong><code>    | Some x -&gt; f x</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val bind : 'a option -&gt; ('a -&gt; 'b option) -&gt; 'b option = &lt;fun&gt;</code></pre><p>As you can see, <code>bind None f</code> returns <code>None</code> without calling <code>f</code>, and
          <code>bind (Some x) f</code> returns <code>f
          x</code>.  <code>bind</code> can be used as a way of sequencing
        together error-producing functions so that the first one to produce an error terminates the
        computation. Here's a rewrite of <code>compute_bounds</code> to use a
        nested series of <code>bind</code>s:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 12)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let compute_bounds ~cmp list =</code></strong>
<strong><code>    let sorted = List.sort ~cmp list in</code></strong>
<strong><code>    Option.bind (List.hd sorted) (fun first -&gt;</code></strong>
<strong><code>      Option.bind (List.last sorted) (fun last -&gt;</code></strong>
<strong><code>        Some (first,last)))</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val compute_bounds : cmp:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>The preceding code is a little bit hard to swallow, however, on a
      syntactic level. We can make it easier to read and drop some of the
      parentheses, by using the infix operator form of
      <code>bind</code>, which we get access to by locally opening
      <code>Option.Monad_infix</code>. The module is
      called <code>Monad_infix</code> because the
      <code>bind</code> operator is part of a subinterface called
      <code>Monad</code>, which we'll see again in <a href="#concurrent-programming-with-async" data-type="xref">#concurrent-programming-with-async</a>:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 13)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let compute_bounds ~cmp list =</code></strong>
<strong><code>    let open Option.Monad_infix in</code></strong>
<strong><code>    let sorted = List.sort ~cmp list in</code></strong>
<strong><code>    List.hd sorted   &gt;&gt;= fun first -&gt;</code></strong>
<strong><code>    List.last sorted &gt;&gt;= fun last  -&gt;</code></strong>
<strong><code>    Some (first,last)</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val compute_bounds : cmp:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>This use of <code>bind</code> isn't really
      materially better than the one we started with, and indeed, for small
      examples like this, direct matching of options is generally better than
      using <code>bind</code>. But for large, complex
      examples with many stages of error handling, the <code>bind</code>
      idiom becomes clearer and easier to manage.</p><p>There are other useful idioms encoded in the functions in <code>Option</code>. One example is <code>Option.both</code>, which takes two optional values
      and produces a new optional pair that is <code>None</code> if either of its arguments are <code>None</code>. Using <code>Option.both</code>, we can make <code>compute_bounds</code> even shorter:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 14)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let compute_bounds ~cmp list =</code></strong>
<strong><code>    let sorted = List.sort ~cmp list in</code></strong>
<strong><code>    Option.both (List.hd sorted) (List.last sorted)</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val compute_bounds : cmp:('a -&gt; 'a -&gt; int) -&gt; 'a list -&gt; ('a * 'a) option =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>These error-handling functions are valuable because they let you
      express your error handling both explicitly and concisely. We've only
      discussed these functions in the context of the <code>Option</code> module, but more functionality of this
      kind can be found in the <code>Result</code> and
      <code>Or_error</code> modules.<a data-type="indexterm" data-startref="erraware">&#xa0;</a><a data-type="indexterm" data-startref="EHeraware">&#xa0;</a></p></section></section><section id="exceptions" data-type="sect1"><h1>Exceptions</h1><p>Exceptions in OCaml are not that different from exceptions in many
    other languages, like Java, C#, and Python. Exceptions are a way to
    terminate a computation and report an error, while providing a mechanism
    to catch and handle (and possibly recover from) exceptions that are
    triggered by subcomputations.<a data-type="indexterm" data-primary="exceptions" data-secondary="usefulness of">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exceptions">&#xa0;</a></p><p>You can trigger an exception by, for example, dividing an integer by
    zero:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 15)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>3 / 0;;</code></strong>
<code class="computeroutput">Exception: Division_by_zero.</code></pre><p>And an exception can terminate a computation even if it happens
    nested somewhere deep within it:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 16)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>List.map ~f:(fun x -&gt; 100 / x) [1;3;0;4];;</code></strong>
<code class="computeroutput">Exception: Division_by_zero.</code></pre><p>If we put a <code>printf</code> in the middle
    of the computation, we can see that <code>List.map</code> is interrupted partway through its
    execution, never getting to the end of the list:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 17)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>List.map ~f:(fun x -&gt; printf "%d\n%!" x; 100 / x) [1;3;0;4];;</code></strong>
<code class="computeroutput">1</code>
<code class="computeroutput">3</code>
<code class="computeroutput">0</code>
<code class="computeroutput">Exception: Division_by_zero.</code></pre><p>In addition to built-in exceptions like <code>Divide_by_zero</code>, OCaml lets you define your
    own:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 18)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>exception Key_not_found of string;;</code></strong>
<code class="computeroutput">exception Key_not_found of string</code>
<code class="prompt"># </code><strong><code>raise (Key_not_found "a");;</code></strong>
<code class="computeroutput">Exception: Key_not_found("a").</code></pre><p>Exceptions are ordinary values and can be manipulated just like
    other OCaml values:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 19)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let exceptions = [ Not_found; Division_by_zero; Key_not_found "b" ];;</code></strong>
<code class="computeroutput">val exceptions : exn list = [Not_found; Division_by_zero; Key_not_found("b")]</code>
<code class="prompt"># </code><strong><code>List.filter exceptions  ~f:(function</code></strong>
<strong><code>    | Key_not_found _ | Not_found -&gt; true</code></strong>
<strong><code>    | _ -&gt; false);;</code></strong>
<code class="computeroutput">- : exn list = [Not_found; Key_not_found("b")]</code></pre><p>Exceptions are all of the same type, <code>exn</code>. The <code>exn</code>
    type is something of a special case in the OCaml type system. It is
    similar to the variant types we encountered in <a href="#variants" data-type="xref">#variants</a>, except that it is <em>open</em>,
    meaning that it's not fully defined in any one place. In particular, new
    tags (specifically, new exceptions) can be added to it by different parts
    of the program. This is in contrast to ordinary variants, which are
    defined with a closed universe of available tags. One result of this is
    that you can never have an exhaustive match on an <code>exn</code>, since the full set of possible exceptions
    is not known.<a data-type="indexterm" data-primary="exn type">&#xa0;</a></p><p>The following function uses the <code>Key_not_found</code> exception we defined above to
    signal an error:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 20)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let rec find_exn alist key = match alist with</code></strong>
<strong><code>    | [] -&gt; raise (Key_not_found key)</code></strong>
<strong><code>    | (key',data) :: tl -&gt; if key = key' then data else find_exn tl key</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val find_exn : (string * 'a) list -&gt; string -&gt; 'a = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>let alist = [("a",1); ("b",2)];;</code></strong>
<code class="computeroutput">val alist : (string * int) list = [("a", 1); ("b", 2)]</code>
<code class="prompt"># </code><strong><code>find_exn alist "a";;</code></strong>
<code class="computeroutput">- : int = 1</code>
<code class="prompt"># </code><strong><code>find_exn alist "c";;</code></strong>
<code class="computeroutput">Exception: Key_not_found("c").</code></pre><p>Note that we named the function <code>find_exn</code> to warn the user that the function
    routinely throws exceptions, a convention that is used heavily in
    Core.<a data-type="indexterm" data-primary="functions" data-secondary="exception warnings for">&#xa0;</a><a data-type="indexterm" data-primary="find_exn function">&#xa0;</a></p><p>In the preceding example, <code>raise</code>
    throws the exception, thus terminating the computation. The type of raise
    is a bit surprising when you first see it:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 21)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>raise;;</code></strong>
<code class="computeroutput">- : exn -&gt; 'a = &lt;fun&gt;</code></pre><p>The return type of <code>'a</code> makes it
    look like <code>raise</code> manufactures a value to
    return that is completely unconstrained in its type. That seems
    impossible, and it is. Really, <code>raise</code>
    has a return type of <code>'a</code> because it
    never returns at all. This behavior isn't restricted to functions like
    <code>raise</code> that terminate by throwing
    exceptions. Here's another example of a function that doesn't return a
    value:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
    (part 22)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let rec forever () = forever ();;</code></strong>
<code class="computeroutput">val forever : unit -&gt; 'a = &lt;fun&gt;</code></pre><p><code>forever</code> doesn't return a value
    for a different reason: it's an infinite loop.</p><p>This all matters because it means that the return type of <code>raise</code> can be whatever it needs to be to fit into
    the context it is called in. Thus, the type system will let us throw an
    exception anywhere in a program.<a data-type="indexterm" data-primary="sexp declaration">&#xa0;</a><a data-type="indexterm" data-primary="exceptions" data-secondary="textual representation of">&#xa0;</a></p><div class="allow_break" data-type="note"><h1>Declaring Exceptions Using with sexp</h1><p>OCaml can't always generate a useful textual representation of an
      exception. For example:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 23)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>exception Wrong_date of Date.t;;</code></strong>
<code class="computeroutput">exception Wrong_date of Date.t</code>
<code class="prompt"># </code><strong><code>Wrong_date (Date.of_string "2011-02-23");;</code></strong>
<code class="computeroutput">- : exn = Wrong_date(_)</code></pre><p>But if we declare the exception using <code>with sexp</code> (and the constituent types have sexp
      converters), we'll get something with more information:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 24)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>exception Wrong_date of Date.t with sexp;;</code></strong>
<code class="computeroutput">exception Wrong_date of Date.t</code>
<code class="prompt"># </code><strong><code>Wrong_date (Date.of_string "2011-02-23");;</code></strong>
<code class="computeroutput">- : exn = (//toplevel//.Wrong_date 2011-02-23)</code></pre><p>The period in front of <code>Wrong_date</code> is there because the representation
      generated by <code>with sexp</code> includes the
      full module path of the module where the exception in question is
      defined. In this case, the string <code>//toplevel//</code> is used to indicate that this was
      declared at the toplevel, rather than in a module.</p><p>This is all part of the support for s-expressions provided by the
      Sexplib library and syntax extension, which is described in more detail
      in <a href="#data-serialization-with-s-expressions" data-type="xref">#data-serialization-with-s-expressions</a>.</p></div><section id="helper-functions-for-throwing-exceptions" data-type="sect2"><h2>Helper Functions for Throwing Exceptions</h2><p>OCaml and Core provide a number of helper functions to simplify
      the task of throwing exceptions. The simplest one is <code>failwith</code>, which could be defined as
      follows:<a data-type="indexterm" data-primary="exceptions" data-secondary="helper functions for">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exception helper functions">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 25)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let failwith msg = raise (Failure msg);;</code></strong>
<code class="computeroutput">val failwith : string -&gt; 'a = &lt;fun&gt;</code></pre><p>There are several other useful functions for raising exceptions,
      which can be found in the API documentation for the <code>Common</code> and <code>Exn</code> modules in Core.</p><p>Another important way of throwing an exception is the <code>assert</code> directive. <code>assert</code> is used for situations where a
      violation of the condition in question indicates a bug. Consider the
      following piece of code for zipping together two lists:<a data-type="indexterm" data-primary="assert directive">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 26)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let merge_lists xs ys ~f =</code></strong>
<strong><code>    if List.length xs &lt;&gt; List.length ys then None</code></strong>
<strong><code>    else</code></strong>
<strong><code>      let rec loop xs ys =</code></strong>
<strong><code>        match xs,ys with</code></strong>
<strong><code>        | [],[] -&gt; []</code></strong>
<strong><code>        | x::xs, y::ys -&gt; f x y :: loop xs ys</code></strong>
<strong><code>        | _ -&gt; assert false</code></strong>
<strong><code>      in</code></strong>
<strong><code>      Some (loop xs ys)</code></strong>
<strong><code>   ;;</code></strong>
<code class="computeroutput">val merge_lists : 'a list -&gt; 'b list -&gt; f:('a -&gt; 'b -&gt; 'c) -&gt; 'c list option =</code>
<code class="computeroutput">  &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>merge_lists [1;2;3] [-1;1;2] ~f:(+);;</code></strong>
<code class="computeroutput">- : int list option = Some [0; 3; 5]</code>
<code class="prompt"># </code><strong><code>merge_lists [1;2;3] [-1;1] ~f:(+);;</code></strong>
<code class="computeroutput">- : int list option = None</code></pre><p>Here we use <code>assert false</code>, which
      means that the <code>assert</code> is guaranteed to trigger. In
      general, one can put an arbitrary condition in the assertion.</p><p>In this case, the <code>assert</code> can never be triggered
      because we have a check that makes sure that the lists are of the same
      length before we call <code>loop</code>. If we
      change the code so that we drop this test, then we can trigger the
      <code>assert</code>:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 27)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let merge_lists xs ys ~f =</code></strong>
<strong><code>    let rec loop xs ys =</code></strong>
<strong><code>      match xs,ys with</code></strong>
<strong><code>      | [],[] -&gt; []</code></strong>
<strong><code>      | x::xs, y::ys -&gt; f x y :: loop xs ys</code></strong>
<strong><code>      | _ -&gt; assert false</code></strong>
<strong><code>    in</code></strong>
<strong><code>    loop xs ys</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val merge_lists : 'a list -&gt; 'b list -&gt; f:('a -&gt; 'b -&gt; 'c) -&gt; 'c list = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>merge_lists [1;2;3] [-1] ~f:(+);;</code></strong>
<code class="computeroutput">Exception: (Assert_failure //toplevel// 5 13).</code></pre><p>This shows what's special about <code>assert</code>: it captures the line number and
      character offset of the source location from which the assertion was
      made.</p></section><section id="exception-handlers" data-type="sect2"><h2>Exception Handlers</h2><p>So far, we've only seen exceptions fully terminate the execution
      of a computation. But often, we want a program to be able to respond to
      and recover from an exception. This is achieved through the use of
      <em>exception handlers</em>.<a data-type="indexterm" data-primary="exceptions" data-secondary="exception handlers">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exception handlers">&#xa0;</a></p><p>In OCaml, an exception handler is declared using a <code>try</code>/<code>with</code>
      statement. Here's the basic syntax.</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/try_with.syntax" class="orm:hideurl:ital"><em class="hyperlink">Syntax</em></a></p><pre data-type="programlisting" data-code-language="ocaml">try <em>&lt;expr&gt;</em> with
| <em>&lt;pat1&gt;</em> -&gt; <em>&lt;expr1&gt;</em>
| <em>&lt;pat2&gt;</em> -&gt; <em>&lt;expr2&gt;</em>
...</pre><p>A <code>try/with</code> clause first evaluates its body,
            <em><code>expr</code></em>. If no exception is thrown,
        then the result of evaluating the body is what the entire <code>try/with</code> clause evaluates to.</p><p>But if the evaluation of the body throws an exception, then the
      exception will be fed to the pattern-match statements following the
      <code>with</code>. If the exception matches a
      pattern, then we consider the exception caught, and the <code>try/with</code> clause evaluates to the expression on
      the righthand side of the matching pattern.</p><p>Otherwise, the original exception continues up the stack of
      function calls, to be handled by the next outer exception handler. If
      the exception is never caught, it terminates the program.</p></section><section id="cleaning-up-in-the-presence-of-exceptions" data-type="sect2"><h2>Cleaning Up in the Presence of Exceptions</h2><p>One headache with exceptions is that they can terminate your
      execution at unexpected places, leaving your program in an awkward
      state. Consider the following function for loading a file full of
      reminders, formatted as s-expressions:<a data-type="indexterm" data-primary="exceptions" data-secondary="exception clean up">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exception clean up">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 28)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let reminders_of_sexp =</code></strong>
<strong><code>    &lt;:of_sexp&lt;(Time.t * string) list&gt;&gt;</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val reminders_of_sexp : Sexp.t -&gt; (Time.t * string) list = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>let load_reminders filename =</code></strong>
<strong><code>    let inc = In_channel.create filename in</code></strong>
<strong><code>    let reminders = reminders_of_sexp (Sexp.input_sexp inc) in</code></strong>
<strong><code>    In_channel.close inc;</code></strong>
<strong><code>    reminders</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val load_reminders : string -&gt; (Time.t * string) list = &lt;fun&gt;</code></pre><p>The problem with this code is that the function that loads the
      s-expression and parses it into a list of <code>Time.t</code>/<code>string</code> pairs might throw an exception if the
      file in question is malformed. Unfortunately, that means that the
      <code>In_channel.t</code> that was opened will
      never be closed, leading to a file-descriptor leak.</p><p>We can fix this using Core's <code>protect</code> function, which takes two arguments: a
      thunk <code>f</code>, which is the main body of
      the computation to be run; and a thunk <code>finally</code>, which is to be called when <code>f</code> exits, whether it exits normally or with an
      exception. This is similar to the <code>try/finally</code> construct available in many
      programming languages, but it is implemented in a library, rather than
      being a built-in primitive. Here's how it could be used to fix <code>load_reminders</code>:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 29)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let load_reminders filename =</code></strong>
<strong><code>    let inc = In_channel.create filename in</code></strong>
<strong><code>    protect ~f:(fun () -&gt; reminders_of_sexp (Sexp.input_sexp inc))</code></strong>
<strong><code>      ~finally:(fun () -&gt; In_channel.close inc)</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val load_reminders : string -&gt; (Time.t * string) list = &lt;fun&gt;</code></pre><p>This is a common enough problem that <code>In_channel</code> has a function called <code>with_file</code> that automates this pattern:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 30)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let reminders_of_sexp filename =</code></strong>
<strong><code>    In_channel.with_file filename ~f:(fun inc -&gt;</code></strong>
<strong><code>      reminders_of_sexp (Sexp.input_sexp inc))</code></strong>
<strong><code>  ;;</code></strong>
<code class="computeroutput">val reminders_of_sexp : string -&gt; (Time.t * string) list = &lt;fun&gt;</code></pre><p><code>In_channel.with_file</code> is built
      on top of <code>protect</code> so that it can
      clean up after itself in the presence of exceptions.</p></section><section id="catching-specific-exceptions" data-type="sect2"><h2>Catching Specific Exceptions</h2><p>OCaml's exception-handling system allows you to tune your
      error-recovery logic to the particular error that was thrown. For
      example, <code>List.find_exn</code> throws
      <code>Not_found</code> when the element in
      question can't be found. Let's look at an example of how you could take
      advantage of this. In particular, consider the following
      function:<a data-type="indexterm" data-primary="exceptions" data-secondary="catching specific">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exception detection">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 31)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let lookup_weight ~compute_weight alist key =</code></strong>
<strong><code>    try</code></strong>
<strong><code>      let data = List.Assoc.find_exn alist key in</code></strong>
<strong><code>      compute_weight data</code></strong>
<strong><code>    with</code></strong>
<strong><code>      Not_found -&gt; 0. ;;</code></strong>
<code class="computeroutput">val lookup_weight :</code>
<code class="computeroutput">  compute_weight:('a -&gt; float) -&gt; ('b, 'a) List.Assoc.t -&gt; 'b -&gt; float =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>As you can see from the type, <code>lookup_weight</code> takes an association list, a key
      for looking up a corresponding value in that list, and a function for
      computing a floating-point weight from the looked-up value. If no value
      is found, then a weight of <code>0.</code> should
      be returned.</p><p>The use of exceptions in this code, however, presents some
      problems. In particular, what happens if <code>compute_weight</code> throws an exception? Ideally,
      <code>lookup_weight</code> should propagate that
      exception on, but if the exception happens to be <code>Not_found</code>, then that's not what will
      happen:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 32)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>lookup_weight ~compute_weight:(fun _ -&gt; raise Not_found)</code></strong>
<strong><code>    ["a",3; "b",4] "a" ;;</code></strong>
<code class="computeroutput">- : float = 0.</code></pre><p>This kind of problem is hard to detect in advance because the type
      system doesn't tell you what exceptions a given function might throw.
      For this reason, it's generally better to avoid relying on the identity
      of the exception to determine the nature of a failure. A better approach
      is to narrow the scope of the exception handler, so that when it fires
      it's very clear what part of the code failed:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 33)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let lookup_weight ~compute_weight alist key =</code></strong>
<strong><code>    match</code></strong>
<strong><code>      try Some (List.Assoc.find_exn alist key)</code></strong>
<strong><code>      with _ -&gt; None</code></strong>
<strong><code>    with</code></strong>
<strong><code>    | None -&gt; 0.</code></strong>
<strong><code>    | Some data -&gt; compute_weight data ;;</code></strong>
<code class="computeroutput">val lookup_weight :</code>
<code class="computeroutput">  compute_weight:('a -&gt; float) -&gt; ('b, 'a) List.Assoc.t -&gt; 'b -&gt; float =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre><p>At this point, it makes sense to simply use the
      nonexception-throwing function, <code>List.Assoc.find</code>, instead:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 34)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let lookup_weight ~compute_weight alist key =</code></strong>
<strong><code>    match List.Assoc.find alist key with</code></strong>
<strong><code>    | None -&gt; 0.</code></strong>
<strong><code>    | Some data -&gt; compute_weight data ;;</code></strong>
<code class="computeroutput">val lookup_weight :</code>
<code class="computeroutput">  compute_weight:('a -&gt; float) -&gt; ('b, 'a) List.Assoc.t -&gt; 'b -&gt; float =</code>
<code class="computeroutput">  &lt;fun&gt;</code></pre></section><section id="backtraces" data-type="sect2"><h2>Backtraces</h2><p>A big part of the value of exceptions is that they provide useful
      debugging information in the form of a stack backtrace. Consider the
      following simple program<a data-type="indexterm" data-primary="debugging" data-secondary="stack backtraces">&#xa0;</a><a data-type="indexterm" data-primary="stack backtraces">&#xa0;</a><a data-type="indexterm" data-primary="backtraces">&#xa0;</a>:<a data-type="indexterm" data-primary="exceptions" data-secondary="stack backtraces for">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="exception backtracing">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/blow_up.ml" class="orm:hideurl:ital"><em class="hyperlink">OCaml</em></a></p><pre data-type="programlisting" data-code-language="ocaml">open Core.Std
exception Empty_list

let list_max = function
  | [] -&gt; raise Empty_list
  | hd :: tl -&gt; List.fold tl ~init:hd ~f:(Int.max)

let () =
  printf "%d\n" (list_max [1;2;3]);
  printf "%d\n" (list_max [])</pre><p>If we build and run this program, we'll get a stack backtrace that
      will provide some information about where the error occurred and the
      stack of function calls that were in place at the time of the
      error:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/build_blow_up.out" class="orm:hideurl:ital"><em class="hyperlink">Terminal</em></a></p><pre data-type="programlisting" data-code-language="console"><code class="prompt">$ </code><strong><code>corebuild blow_up.byte</code></strong>
<code class="prompt">$ </code><strong><code>./blow_up.byte</code></strong>
<code class="computeroutput">3</code>
<code class="computeroutput">Fatal error: exception Blow_up.Empty_list</code>
<code class="computeroutput">Raised at file "blow_up.ml", line 5, characters 16-26</code>
<code class="computeroutput">Called from file "blow_up.ml", line 10, characters 17-28</code></pre><p>You can also capture a backtrace within your program by calling
      <code>Exn.backtrace</code>, which returns the
      backtrace of the most recently thrown exception. This is useful for
      reporting detailed information on errors that did not cause your program
      to fail.<a data-type="indexterm" data-primary="Exn module" data-secondary="Exn.backtrace">&#xa0;</a></p><p>This works well if you have backtraces enabled, but that isn't
      always the case. In fact, by default, OCaml has backtraces turned off,
      and even if you have them turned on at runtime, you can't get backtraces
      unless you have compiled with debugging symbols. Core reverses the
      default, so if you're linking in Core, you will have backtraces enabled
      by default.</p><p>Even using Core and compiling with debugging symbols, you can turn
      backtraces off by setting the <code>OCAMLRUNPARAM</code> environment variable to be
      empty:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/build_blow_up_notrace.out" class="orm:hideurl:ital"><em class="hyperlink">Terminal</em></a></p><pre data-type="programlisting" data-code-language="console"><code class="prompt">$ </code><strong><code>corebuild blow_up.byte</code></strong>
<code class="prompt">$ </code><strong><code>OCAMLRUNPARAM= ./blow_up.byte</code></strong>
<code class="computeroutput">3</code>
<code class="computeroutput">Fatal error: exception Blow_up.Empty_list</code></pre><p>The resulting error message is considerably less informative. You
      can also turn backtraces off in your code by calling <code>Backtrace.Exn.set_recording false</code>.<a data-type="indexterm" data-primary="Exn module" data-secondary="Backtrace.Exn.set_recording false">&#xa0;</a></p><p>There is a legitimate reasons to run without backtraces: speed.
      OCaml's exceptions are fairly fast, but they're even faster still if you
      disable backtraces. Here's a simple benchmark that shows the effect,
      using the <code>core_bench</code> package:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/exn_cost.ml" class="orm:hideurl:ital"><em class="hyperlink">OCaml</em></a></p><pre data-type="programlisting" data-code-language="ocaml">open Core.Std
open Core_bench.Std

let simple_computation () =
  List.range 0 10
  |&gt; List.fold ~init:0 ~f:(fun sum x -&gt; sum + x * x)
  |&gt; ignore

let simple_with_handler () =
  try simple_computation () with Exit -&gt; ()

let end_with_exn () =
  try
    simple_computation ();
    raise Exit
  with Exit -&gt; ()

let () =
  [ Bench.Test.create ~name:"simple computation"
      (fun () -&gt; simple_computation ());
    Bench.Test.create ~name:"simple computation w/handler"
      (fun () -&gt; simple_with_handler ());
    Bench.Test.create ~name:"end with exn"
      (fun () -&gt; end_with_exn ());
  ]
  |&gt; Bench.make_command
  |&gt; Command.run</pre><p>We're testing three cases here: a simple computation with no
      exceptions; the same computation with an exception handler but no thrown
      exceptions; and finally the same computation where we use the exception
      to do the control flow back to the caller.</p><p>If we run this with stacktraces on, the benchmark results look
      like this:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/run_exn_cost.out" class="orm:hideurl:ital"><em class="hyperlink">Terminal</em></a></p><pre data-type="programlisting" data-code-language="console"><code class="prompt">$ </code><strong><code>corebuild -pkg core_bench exn_cost.native</code></strong>
<code class="prompt">$ </code><strong><code>./exn_cost.native -ascii cycles</code></strong>
<code class="computeroutput">Estimated testing time 30s (change using -quota SECS).</code>
<code class="computeroutput">                                                                </code>
<code class="computeroutput">  Name                           Cycles   Time (ns)   % of max  </code>
<code class="computeroutput"> ------------------------------ -------- ----------- ---------- </code>
<code class="computeroutput">  simple computation                279         117      76.40  </code>
<code class="computeroutput">  simple computation w/handler      308         129      84.36  </code>
<code class="computeroutput">  end with exn                      366         153     100.00  </code>
<code class="computeroutput">                                                                </code></pre><p>Here, we see that we lose something like 30 cycles to adding an exception handler, and
        60 more to actually throwing and catching an exception. If we turn backtraces off, then the
        results look like this:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/run_exn_cost_notrace.out" class="orm:hideurl:ital"><em class="hyperlink">Terminal</em></a></p><pre data-type="programlisting" data-code-language="console"><code class="prompt">$ </code><strong><code>OCAMLRUNPARAM= ./exn_cost.native -ascii cycles</code></strong>
<code class="computeroutput">Estimated testing time 30s (change using -quota SECS).</code>
<code class="computeroutput">                                                                </code>
<code class="computeroutput">  Name                           Cycles   Time (ns)   % of max  </code>
<code class="computeroutput"> ------------------------------ -------- ----------- ---------- </code>
<code class="computeroutput">  simple computation                279         116      83.50  </code>
<code class="computeroutput">  simple computation w/handler      308         128      92.09  </code>
<code class="computeroutput">  end with exn                      334         140     100.00  </code>
<code class="computeroutput">                                                                </code></pre><p>Here, the handler costs about the same, but the exception itself costs only 25, as
        opposed to 60 additional cycles. All told, this should only matter if you're using
        exceptions routinely as part of your flow control, which is in most cases a stylistic
        mistake anyway.</p></section><section id="from-exceptions-to-error-aware-types-and-back-again" data-type="sect2"><h2>From Exceptions to Error-Aware Types and Back Again</h2><p>Both exceptions and error-aware types are necessary parts of
      programming in OCaml. As such, you often need to move between these two
      worlds. Happily, Core comes with some useful helper functions to help
      you do just that. For example, given a piece of code that can throw an
      exception, you can capture that exception into an option as
      follows:<a data-type="indexterm" data-primary="exceptions" data-secondary="and error-aware types">&#xa0;</a><a data-type="indexterm" data-primary="error-aware return types">&#xa0;</a><a data-type="indexterm" data-primary="error handling" data-secondary="combining exceptions and error-aware types">&#xa0;</a></p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 35)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let find alist key =</code></strong>
<strong><code>    Option.try_with (fun () -&gt; find_exn alist key) ;;</code></strong>
<code class="computeroutput">val find : (string * 'a) list -&gt; string -&gt; 'a option = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>find ["a",1; "b",2] "c";;</code></strong>
<code class="computeroutput">- : int option = None</code>
<code class="prompt"># </code><strong><code>find ["a",1; "b",2] "b";;</code></strong>
<code class="computeroutput">- : int option = Some 2</code></pre><p>And <code>Result</code> and <code>Or_error</code> have similar <code>try_with</code> functions. So, we could write:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 36)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>let find alist key =</code></strong>
<strong><code>    Or_error.try_with (fun () -&gt; find_exn alist key) ;;</code></strong>
<code class="computeroutput">val find : (string * 'a) list -&gt; string -&gt; 'a Or_error.t = &lt;fun&gt;</code>
<code class="prompt"># </code><strong><code>find ["a",1; "b",2] "c";;</code></strong>
<code class="computeroutput">- : int Or_error.t = Core_kernel.Result.Error ("Key_not_found(\"c\")")</code></pre><p>And then we can reraise that exception:</p><p><a href="https://github.com/realworldocaml/examples/tree/v1/code/error-handling/main.topscript" class="orm:hideurl:ital"><em class="hyperlink">OCaml utop</em></a>
      (part 37)</p><pre data-type="programlisting" data-code-language="ocaml"><code class="prompt"># </code><strong><code>Or_error.ok_exn (find ["a",1; "b",2] "b");;</code></strong>
<code class="computeroutput">- : int = 2</code>
<code class="prompt"># </code><strong><code>Or_error.ok_exn (find ["a",1; "b",2] "c");;</code></strong>
<code class="computeroutput">Exception: ("Key_not_found(\"c\")").</code></pre></section></section><section id="choosing-an-error-handling-strategy" data-type="sect1"><h1>Choosing an Error-Handling Strategy</h1><p>Given that OCaml supports both exceptions and error-aware return
    types, how do you choose between them? The key is to think about the
    trade-off between concision and explicitness.<a data-type="indexterm" data-primary="error handling" data-secondary="strategy choice" data-seealso="errors">&#xa0;</a></p><p>Exceptions are more concise because they allow you to defer the job of error handling to
      some larger scope, and because they don't clutter up your types. But this concision comes at a
      cost: exceptions are all too easy to ignore. Error-aware return types, on the other hand, are
      fully manifest in your type definitions, making the errors that your code might generate
      explicit and impossible to ignore.<a data-type="indexterm" data-primary="exceptions" data-secondary="benefits and drawbacks of">&#xa0;</a></p><p>The right trade-off depends on your application. If you're writing a
    rough-and-ready program where getting it done quickly is key and failure
    is not that expensive, then using exceptions extensively may be the way to
    go. If, on the other hand, you're writing production software whose
    failure is costly, then you should probably lean in the direction of using
    error-aware return types.</p><p>To be clear, it doesn't make sense to avoid exceptions entirely. The
    maxim of "use exceptions for exceptional conditions" applies. If an error
    occurs sufficiently rarely, then throwing an exception is often the right
    behavior.</p><p>Also, for errors that are omnipresent, error-aware return types may
    be overkill. A good example is out-of-memory errors, which can occur
    anywhere, and so you'd need to use error-aware return types everywhere to
    capture those. Having every operation marked as one that might fail is no
    more explicit than having none of them marked.</p><p>In short, for errors that are a foreseeable and ordinary part of the
    execution of your production code and that are not omnipresent,
    error-aware return types are typically the right solution.</p></section></section>
